# Generated by Django 5.2.3 on 2025-06-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bautizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nuevo_creyente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='otros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiene_ministerio',
            field=models.BooleanField(default=False),
        ),
    ]
