# Generated by Django 5.2.3 on 2025-06-27 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nivel_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('profesor_asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asistente', to=settings.AUTH_USER_MODEL)),
                ('profesor_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_titular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnos', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'alumno'}, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('horarios', models.ManyToManyField(to='core.horario')),
                ('profesores', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profesorcurso')),
            ],
        ),
    ]
