# Generated by Django 5.2.3 on 2025-06-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_alergias_usuario_bautizado_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tiene_ministerio',
            new_name='ministerio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='otros',
        ),
    ]
