# Generated by Django 5.2.3 on 2025-06-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tiene_ministerio_usuario_ministerio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ministerio',
            new_name='tiene_ministerio',
        ),
    ]
