# Generated by Django 5.2.3 on 2025-06-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nota_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='total_sesiones',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
