# Generated by Django 5.2.3 on 2025-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_horario_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='horarios',
        ),
        migrations.AddField(
            model_name='curso',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='core.horario'),
        ),
    ]
