# Generated by Django 5.2.3 on 2025-06-30 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_clase_horarios_curso_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesorcurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profesorcurso',
            name='profesor_asistente',
        ),
        migrations.RemoveField(
            model_name='profesorcurso',
            name='profesor_titular',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='profesores',
        ),
        migrations.AddField(
            model_name='clase',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='core.horario'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='core.nivel'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor_asistente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor_titular',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_titular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='ProfesorCurso',
        ),
    ]
