# Generated by Django 5.2.3 on 2025-07-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_horario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo'), ('Lunes a Viernes', 'Lunes a Viernes')], max_length=16),
        ),
    ]
