# Generated by Copilot on 2025-07-01
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_horario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fechas_programadas',
            field=models.JSONField(default=list, blank=True, help_text='Lista de fechas programadas para las sesiones de la clase'),
        ),
    ]
