# Generated by Django 5.2.3 on 2025-07-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clase_fechas_programadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
