# Generated by Django 5.2.3 on 2025-07-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_nota_nota1_alter_nota_nota2_alter_nota_nota3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fechas_programadas',
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.clase')),
            ],
        ),
    ]
