# Generated by Django 5.2.3 on 2025-09-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_clase_fechas_programadas_sesionclase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nota1',
            new_name='examen_final',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota2',
            new_name='participacion',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota3',
            new_name='tareas',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota4',
        ),
    ]
