# Generated by Django 5.2.3 on 2025-09-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_nota1_nota_examen_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('archivo', 'Archivo'), ('otro', 'Otro')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.clase')),
            ],
        ),
    ]
