# Generated by Django 5.2.3 on 2025-09-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recursocurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='total_sesiones',
        ),
    ]
