# Generated by Django 5.2.3 on 2025-09-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_clase_total_sesiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='total_sesiones',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
