# Generated by Django 5.2.3 on 2025-09-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clase_total_sesiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='total_sesiones',
            field=models.PositiveIntegerField(),
        ),
    ]
