# Generated by Django 5.2.3 on 2025-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_clase_total_sesiones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='alergias',
            new_name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo_sanguineo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='medicamentos_y_dosis',
            field=models.TextField(blank=True),
        ),
    ]
