# Generated by Django 5.2.3 on 2025-09-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_alergias_usuario_enfermedades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursocurso',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('audio_podcast', 'Audio Podcast'), ('presentacion_ppt', 'Presentación PPT'), ('documento_pdf_word', 'Documento PDF/WORD'), ('imagen_infografia', 'Imagen Infografía'), ('app', 'App'), ('website_red_social', 'Website o Red Social')], max_length=50),
        ),
    ]
