# Generated by Django 5.2.3 on 2025-10-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_recursocurso_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='participacion',
            new_name='participacion_1',
        ),
        migrations.AddField(
            model_name='nota',
            name='participacion_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='nota',
            name='participacion_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
