# Generated by Django 5.2.3 on 2026-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_participacion_nota_participacion_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
